name: Netlify Document Staging Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publishMasterCommit:
    name: Deploying on Netlify Document Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document/website
      - name: Replace kucLink
        run: sed -i 's|https://unpkg.com/kintone-ui-component/umd/kuc.min.js|/js/kuc.min.js|' kuc-loader.js
        working-directory: docs/document/website/static/js
      - name: Install dependencies on root
        run: npm ci
      - name: Build umd file
        run: npm run build:umd_prod
      - name: Move umd file
        run: mv umd/kuc.min.js docs/document/website/static/js
      - name: Build document
        run: npm run build
        working-directory: docs/document/website
      - name: Install Netlify
        run: npm i netlify-cli@9 --no-save
      - name: Deploy
        run: netlify deploy --dir=./docs/document/website/build/kintone-ui-component --alias=staging --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_DOCUMENT_ID }}
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.WORKFLOW_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://staging--kintone-ui-component.netlify.app
