name: Netlify Document Production Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publishOnMasterRelease:
    name: Deploying on Netlify Document Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document/website
      - name: Build document
        run: npm run build
        working-directory: docs/document/website
      - name: Install Netlify
        run: npm i netlify-cli --no-save
      - name: Deploy
        run: npx netlify deploy --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}