name: Netlify Document Production Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publishOnMasterRelease:
    name: Deploying on Netlify Document Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document/website
      - name: Build document
        run: npm run build
        working-directory: docs/document/website
      - name: Deploying on Netlify Production Environment
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCUMENT_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './docs/document/website/build/kintone-ui-component'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
